name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Download VERSION
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: version
      - name: Add Version to environment
        run: |
          echo "VERSION=$(<version.txt)" >> $GITHUB_ENV
      - name: Download Linux ARM32 ZIP
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: linux-zip-arm32
          path: target/install
      - name: Delete old release if exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        continue-on-error: true
        with:
          delete_release: true
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create relase body
        run: |
          touch body.md
          if [[ $VERSION == *"SNAPSHOT"* ]]; then
            echo "**These are snapshot builds. Untested and not recommended for daily use.**" >> body.md
          fi

          if [[ $VERSION == *"EA"* ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          fi
      - name: Release nightly build
        uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          name: ${{ env.VERSION }}
          artifacts: target/install/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{  env.VERSION }}
          bodyFile: "body.md"
          prerelease: ${{ env.PRE_RELEASE }}
